server:
  port: 8083

spring:
  application:
    name: eureka-statistics-service
  profiles:
    active: native
  data:
    mongodb:
      host: localhost
      port: 27017
      database: statistics
logging:
  level:
    root: INFO

